name: Publish package to ID mvn repo

#on:
#  release:
#    types: [published]
on:
  push:
    branches:
      - reposilite

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
                "id": "reposilite-repository-releases",
                "username": "${{ secrets.REPOSILITE_USERNAME }}",
                "password": "${{ secrets.REPOSILITE_PASSWORD }}"
            }]
      - name: Publish package
        working-directory: ./lib-ncip-client 
        run: mvn clean deploy -Pdeploy-ncip-client
